

services:
  db:
    image: postgres:15
    container_name: catfood_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catfood
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: catfood_web
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/catfood
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
